### ISSUE TITLE
API: Nefungují rozcestníky se starým formátem ref (xxxx/yyy) 

### ISSUE THREAD

**Issue by mkyral** [osmcz/api#1]
Sice tady ten script zatím chybí, ale api má problém s číslem rozcestníku ve starém formátu s lomítkem.

Tenhle dotaz:
http://api.openstreetmap.cz/table/ref/2250/440?outputFormat=application%2Fjson&output=geojson

mi vrátí:
`{"features":[],"type":"FeatureCollection"}`

**Comment by walley** [comment]
to ma, musim zjistit jakym zpusobem encodovat lomitko aby to nebralo jako lomitko, nebo prizpusobit ziskavani parametru z url

**Comment by zbycz** [comment]
tak co třeba `table?ref=abc/def&output=json` ?

**Comment by walley** [comment]
jelikoz sem nikde nenasel doporuceni jak to resit, bude se proste podle typu dotazu brat lomitko jako soucast hodnoty, napocita to pocet lomitek co sou api call a zbytek uz bude hodnota

**Comment by walley** [comment]
lomitko bych povolil pouze v ref, nikde jinde by se asi vyskytovat nemelo.

**Comment by walley** [comment]
hotovo

**Comment by mkyral** [comment]
Díky,
