### ISSUE TITLE
do ref nelze zadat písmeno s diakritikou (Š)

### ISSUE THREAD

**Issue by mkyral** [osmcz/api#10]
Viz: http://api.openstreetmap.cz/table/id/5842

Číslo rozcestníku je ŠU991 (Šumperk), ale uloženo bylo pouze U991. Zkusil jsem to opravit v editoru, ale dopadlo to stejně.

![guidepost_editor](https://cloud.githubusercontent.com/assets/155542/14408366/1e387d44-fef2-11e5-9df9-b409267e32bf.png)

**Comment by walley** [comment]
to uz je opravene, jen neni zmenene volani api v javascriptu, to bych mohl dneska stihnout
