### ISSUE TITLE
Chybí kontrola na formát souřadnic

### ISSUE THREAD

**Issue by mkyral** [osmcz/api#11]
API nekontroluje formát zadaných souřadnic.

Viz: http://api.openstreetmap.cz/table/id/5842

Nějak jsem se s tou mapou v mini editoru nedokázal dostat na správné místo, tak jsem vzal souřadnice rozcestníku z osm.org, kde byly ve formátu ss,ssss. No a dopadlo to jako ssssss :-D

![guidepost_editor](https://cloud.githubusercontent.com/assets/155542/14408366/1e387d44-fef2-11e5-9df9-b409267e32bf.png)

**Comment by walley** [comment]
porad sem se este nedostal k zadavani souradnic z mapy.

zkusim s tim neco udelat.

**Comment by mkyral** [comment]
Nicméně to s tímhle issue souvisí jen okrajově. API by mělo tyhle souřadnice odmítnout nebo korektně zpracovat ne?

**Comment by walley** [comment]
k tomu byla ta druha veta, jako ze zkusim naimplementovat nejaky zakladni test na spravnost formatu. 
Konkretne v tomhle pridape mozna pridam zmenu , na ., proto to neproslo

**Comment by mkyral** [comment]
Aha. Já myslel, že ty dvě věty patří k sobě ;-)

Jinak už nějakou dobu přemýšlím nad nahráváním obrázku rozcestníku přímo z aktivní vrstvy. Vyberu si rozcestník, otevře se mi detail kde bude možnost nahrát obrázek. Něco jako: "Chybí obrázek, Nahrejte jej." 

Souřadnice by se vzaly z rozcestníku, ref třeba taky. Případně by jej uživatel mohl zadat. Ale to budu muset nejprve prozkoumat, jak to máš udělané na old.osm.cz.

**Comment by walley** [comment]
Nahravani se udela uplne znovu. Ale to soucasny lze pouzit samozrejme taky. je to jen multipart formular.

**Comment by walley** [comment]
opraveno
(tedy pouze pri kontrole souradnic z formulare, vadne exif souradnice by meli byt novy bugreport az se vyskytnou)
