### ISSUE TITLE
copyright fotek

### ISSUE THREAD

**Issue by walley** [osmcz/api#16]
v podstate sou ted vsechny fotky podle autorskyho zakona
je potreba umoznit specifikovat licenci pro "rozsirene moznosti sdileni"
a taky umoznit autorum to zpetne zmenit pokud budou chtit

**Comment by walley** [comment]
pridan sloupec license do db
kdyby neco nefungovalo tak je to tim, ze vetsinu selektu indexuju cislem a ne jmenem sloupce:)

potreba dodelat:
moznost zmeny (tam bude potreba nejakej hruzostrasne vypaqdajici pravnickej text kterej bude muset autor odsouhlasit)
zobrazeni
filtrovani

**Comment by mkyral** [comment]
> Moznost zmeny
Akorát by mně zajímalo, jak zajistíš, aby tu licenci změnil jen ten, kdo tam tu fotku nahrál. To bude docela problém.

Jaké licence plánuješ? Jedna speciální nebo jich bude na výběr více? Třeba CC0 nebo jinou CC?  https://creativecommons.org/share-your-work/public-domain/freeworks/

**Comment by walley** [comment]
nejake kombinace cc
plus cokoliv co se da aplikovat na fotky

ja to nijak zjistovat nebudu

ja tam napisu nejakou smlouvu ala wikimedia commons
jakoze blablabla su autor a podle zakona tohoatoho sb. blabla menim licenci na tuhlenctu.

**Comment by walley** [comment]
pridam jeste ty odkazy na shrnuti, cc vypadaji takto https://creativecommons.org/licenses/by/2.0/

**Comment by walley** [comment]
json je zmenen a vraci objekt 2 objektu licenses a sites ze stejnym identifikatorem.

timto je problem vyresen:)
