### ISSUE TITLE
predelat stavajici upload fotek

### ISSUE THREAD

**Issue by walley** [osmcz/api#17]
zaklad je upload formular, mel by se nejak vmestnat do sidebar panelu na openstreetmap.cz,

https://blueimp.github.io/jQuery-File-Upload/jquery-ui.html - nasel sem treba tohle, vypada to zajimave

v dalsi fazi by se melo uploadovani zmenit na editaci zakladnich parametru, neco si server vycte (lokaci) neco bude uzivatel muset zadat sam.
udelat to pro nekolik fotek zaraz, asi tak max 5 protoze vic by asi nikdo nestihal.

**Comment by walley** [comment]
http://designscrazed.org/html5-jquery-file-upload-scripts/

**Comment by mkyral** [comment]
To vypadá pěkně. Tohle by se mohlo taky hodit: https://github.com/exif-js/exif-js

**Comment by mkyral** [comment]
Viz: https://github.com/osmcz/osmcz/issues/120

**Comment by walley** [comment]
asi pouziju toto
frontend:
https://github.com/blueimp/jQuery-File-Upload/
backend:
https://metacpan.org/pod/jQuery::File::Upload

vypada to slozite ale treba to pude.
analyza souboru urcite bude probihat serverside, 

osmcz/osmcz#120 se na to bude muset posleze namontovat, protoze guidepost.php zrusim (blaznivy php sem mel zrusit uz davno:)

**Comment by mkyral** [comment]
> protoze guidepost.php zrusim

No super. Až budeš mít hotové nové api, tak dej vědět. Případně to rovnou uprav.

**Comment by severak** [comment]
Doporučuji serverside detekovat otočení fotografie z exifu a pak jí otočit odpovídajícím způsobem.

**Comment by walley** [comment]
http://api.openstreetmap.cz/webapps/upload.new/

ukazkova pidialpikace, momentalne neni funkcni:)

**Comment by walley** [comment]
https://github.com/walley/api/issues/1
