### ISSUE TITLE
table/name/xxx - časové omezení

### ISSUE THREAD

**Issue by mkyral** [osmcz/api#21]
S tím jak narůstá počet nahraných rozcestníků uživatelem, je tahle stránka čím dál větší a vždy se nahraje komplet. V "all" je stránkování, ale tady ne.

Ovšem ještě lepší než stránkování by bylo nějaké časové omezení. 
Třeba: `table/name/xxx?created=today` - zobrazí všechny fotky, které jsem vložil dnes. Další parametry by mohly být `?created=lastWeek`, `?created=lastMonth` a `?created=lastYear`

Podobně by mohlo existovat i `?modified=...`

**Comment by walley** [comment]
implementoval sem offset parametr, ve spolupraci s limit to udela od-do pro jakykoliv dotaz

nicmene sem jeste nezkousel, jestli to funguje;)

**Comment by walley** [comment]
na pridani timestampu se porad pracuje

**Comment by walley** [comment]
strankovani bylo naimplementovani, na case se pracuje

**Comment by walley** [comment]
pridano api na zjisteni casu vlozeni, tudiz cas se zas o neco priblizil

**Comment by walley** [comment]
https://github.com/walley/api/issues/2
