### ISSUE TITLE
datum fotek

### ISSUE THREAD

**Issue by walley** [osmcz/api#22]
- [x] udelat v db tabuli na datum
- [x] pri vlozeni do tabule vlozit cas
- [x] umoznit prohledavat exif fotky (pro ziskani datumu)
- [x] udelat do api call na datum vlozeni
- [x] udelat do api call na datum porizeni 
- [x] pridat to jako info do editoru

**Comment by walley** [comment]
sqltime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL

**Comment by walley** [comment]
editor zobrazuje datum vytvoreni vytazene z exifu ...

**Comment by walley** [comment]
tabule v db

CREATE TABLE time (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  gp_id integer,
  sqltime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

extra tabule je ze se mi nechce upravovat stavajici dotazy, resp. zjistovat jestli nahodou nepotrebuji upravit

**Comment by mkyral** [comment]
Stejně musíš něco upravit, aby ti to vrátilo datum zároveň s fotkou. Tak proč to neudělat pořádně? Navíc, pokud tam máš "current_timestamp" tak se ta hodnota vloží automaticky a nemusíš vůbec nic řešit.

Extra tabulka = extra insert

**Comment by walley** [comment]
nekdy priste, nejde vsechno naraz

**Comment by walley** [comment]
hotovo, neni to uplne idealni ale je to tam
