### ISSUE TITLE
thumbnail generator

### ISSUE THREAD

**Issue by walley** [osmcz/api#23]
transparent thumbnail generator

**Comment by walley** [comment]
http://phpthumb.sourceforge.net

**Comment by walley** [comment]
phpthumb nainstalovan

**Comment by walley** [comment]
a dokonce i funguje, ted jen poladit konfiguraci a zjistit, kam to vsude nasadit.

**Comment by severak** [comment]
a používá se někde? Třeba rozcestníky na openstretmap.cz načítají plnou fotku.

**Comment by walley** [comment]
Zatim ne

**Comment by mkyral** [comment]
Jak to teda funguje? Jak si mám vyžádat náhled? Má to nějaké kešování? Pro zamýšlený kolotoč fotek u rozcestníků budu náhledy potřebovat.

Asi bude nejlepší rozšířit api, aby posílalo i adresu náhledu, případně zda je dostupno více velikostí. V budoucnu bude možné tu adresu bez problémů změnit.

**Comment by mkyral** [comment]
btw, co nasadit třeba toto: http://search.cpan.org/~scott/Apache-Image-v0.0.4/lib/Apache/Image.pm

**Comment by walley** [comment]
funguje to takto:
http://api.openstreetmap.cz/p/phpThumb.php?src=http://api.openstreetmap.cz/img/guidepost/0052Podol%C3%AD.jpg&w=100&h=100
je vypnuty kesovani, na to asi neni misto

**Comment by mkyral** [comment]
Tak teoreticky bychom to mohli kešovat jinde. Udělat lokální službu pobobnou https_proxy, která by buď hned vrátila obrázek z lokální cache, nebo by zavolala tu url, náhled pak přeposlala a zároveň si jej uložila pro příště.

@tkas ? @zbycz ? Co vy na to? Kolik máme na www.openstreetmap.cz místa? ;-)

**Comment by zbycz** [comment]
Asi by to šlo - kešovat obrázky 100x100 ~ 2kb je v poho. Kolik je celkem vyfocených rozcestníků? :-)

Jen to bude chtít napsat nějaký job na automatické pročišťování keše.

**Comment by walley** [comment]
11000

**Comment by mkyral** [comment]
Aktivní vrstva používá náhledy 250x250

A asi by bylo dobré to volání upravit, aby stačil jen název obrázku. Ne celá url. Takhle si u tebe můžu nechat zmenšit jakýkoli obrázek ;-)

**Comment by mkyral** [comment]
Aktivní vrstva používá náhledy 250x250

A asi by bylo dobré to volání upravit, aby stačil jen název obrázku. Ne celá url. Takhle si u tebe můžu nechat zmenšit jakýkoli obrázek ;-)

**Comment by tkas** [comment]
Na osm.cz je mista zatim dost, kesovat to neni problem, cistit se muze tmpwatchem jako jine veci.

**Comment by walley** [comment]
je vypnut hotlinking.
kes jeste zvazim.
issue zaviram, generator generuje.

**Comment by mkyral** [comment]
Tak keš by se určitě hodila. Ono to generování "on the fly" způsobuje docela nepříjemné poskakování při nahrávání rozcestníků v aktivní vrstvě. A nedej bože když si zavolám api../name/mkyral - to musí uplně zahltit server...

Můžu případně nějak přispět na větší disk? ;-)

**Comment by walley** [comment]
otevri novou issue

**Comment by mkyral** [comment]
No už jsem to vyřešil - Viz dnešní emaily ;-)
