### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by walley** [osmcz/api#24]
prozatim sem rozjel openid prez apache modul. jeste je potreba to naimplementovat.

oauth bych chtel tez aby to fungovalo oproti osm oauth.

**Comment by walley** [comment]
testovat mozno na https://api.openstreetmap.cz/openid/ping
je k tomu potrba samozrejme openid ucet, treba na mojeid.cz

oauth je porad v planu, az se podari tak zustanou nejspis v provozu obe reseni

**Comment by mkyral** [comment]
Otestováno s mojeid. Ponguje to.

**Comment by walley** [comment]
https://api.openstreetmap.cz/openid/authcheck
este sem pridal kontrolu, vypise to jmeno ktere sluzba posle zpet.
Nezadam zadne dalsi informace a to jmeno bude slouzit jako identifikator. Posli mi sem to tvoje a ja ho tam pridam, at nekdo muze vyzkouset jestli to cele vubec funguje;) Potom bych to prepnul na vsechny s validnim openid.

Teoreticky by to melo kazdou akci autoschvalit, coz znamena ze se zmena provede okamzite.

**Comment by mkyral** [comment]
Myslíš tohle? ```go away https://mkyral.mojeid.cz/#0gQJXul3eXh1```

**Comment by walley** [comment]
jojo dik
kdyz to zkusis znovu, melo by to napsat user ok

**Comment by mkyral** [comment]
Jo jo, je to tak: ```https://mkyral.mojeid.cz/#0gQJXul3eXh1 is ok```

**Comment by mkyral** [comment]
> a kazda zmena tebou provedena by mela byt okamzita.
> to /openid/ v url je urcujici, url s /table/ bude fungovat stejne jako predtim.

Zkusil jsem https://api.openstreetmap.cz/openid/ref/KA236 , ale nevím, jestli mne teda poznal (někde by mohla být nějaká ikonka, že jsem přihlášen). Ale asi mne nepoznal, ty tagy, co jsem přidal se hned neobjevily.

> do webu to asi nejak rozumne napasovat nepujde.

Tak teoreticky by šlo do formuláře vedle jména přihodit checkbox nebo odkaz na openid. Když na něj uživatel klikne, tak se provede přihlášení přes openid (stačí zavolat tu adresu openid/authcheck?) a pokud je openid zvalidováno, tak by se volala ta openid adresa.

A mimochodem, to openid funguje jen přes https a ty http odkaze na css a js soubory se FF nelíbí. Bylo by fajn to všechno převést na https.


http://api.openstreetmap.cz/editor.css
http://code.jquery.com/jquery-1.11.3.min.js
http://www.appelsiini.net/download/jquery.jeditable.mini.js
http://api.openstreetmap.cz/wheelzoom.js

**Comment by mkyral** [comment]
Aha. Ono to asi bude chtít změnit v editoru všechna volání "http://api.openstreetmap.cz/table/xxx" na "https://api.openstreetmap.cz/openid/xxx" ;-)

**Comment by walley** [comment]
prez https to funguje a to pouze.

editor se musi upravit to je jasne, pracuje se na tom.
nicmene chci zachovat tu puvodni funkcnost, takze se to musi postelovat aby to fungovalo tak i tak.

**Comment by mkyral** [comment]
Jak to má fungovat?

Zkoušel jsem editovat https://api.openstreetmap.cz/openid/id/3001 a přidal jsem ref a tagy a všechny moje změny stejně čekají na review.

Stejně tak, když jsem zkusil dané změny potvrdit, akorát mi vyskočila hláška "error ."  - to jsem se toho teda dověděl ;-)

Bohužel na lokále to nejsem schopen debugovat, protože nevím jak na vagrant a https :-(

**Comment by mkyral** [comment]
Jo ahá, ono to sice jede přes openid, ale ty změny se pošlou na table. Nedají se ty stringy api.openstreetmap.cz/table nahradit volaným url? - pro table, by to volalo table, pro openid zase openid.

Určitě dalo, ale v perlu to neumím ;-)

**Comment by walley** [comment]
zrovna to predelavam.

editor uz je v podstate funkcni s loginem, jen jeste sem tam neco vola postaru. Asi to komplet cele predelat dnes nestihnu, ale tak do 2 dnu by to melo byt kompletni.

(pak snad uz dodelam ten upload, koukam ze lidi uz zacinaji byt netrpelivi:)

**Comment by mkyral** [comment]
Super. těším se ;-)

**Comment by walley** [comment]
testovani odhalilo zasadni problemy s mixed https content:)
neco moje vina a neco chyba knihovny v js, musim to stahnout lokalne a opravit.

nova verze firefoxu a ostatnich mocne pritvrdili a uz skoro odmitaji cokoliv nacist, ale pude

**Comment by mkyral** [comment]
Jen tak mimochodem. Zkoušel jsem na osmap.cz teď přesunout rozcestník a dopadlo to takto:
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>You can not do this</h1>
<p>to me:(</p>
<hr>
<address>openstreetmap.cz/2 Ulramegasuperdupercool/0.0.1 Server at api.openstreetmap.cz Port 80</address>
</body></html>
```

**Comment by walley** [comment]
kdyz neco nefunguje tak vyrob novej issue
uz to move asi funguje, zapomel sem my, a nejakej jinej request mi zmenil pod rukama dotaz:)

**Comment by walley** [comment]
otestovano a zda se ze vsechno funguje
