### ISSUE TITLE
https

### ISSUE THREAD

**Issue by walley** [osmcz/api#25]
https://letsencrypt.org/getting-started/

**Comment by walley** [comment]
nainstalovano, 
test na https://api.openstreetmap.cz/table/ping
zkuste to nekdo overit:)

**Comment by mkyral** [comment]
Zdá se to funkční:

![https](https://cloud.githubusercontent.com/assets/155542/15647850/9b41550e-2666-11e6-8857-3b21cbd4df47.png)

**Comment by walley** [comment]
commit 92660a2ef97787117bbc0738716c529f6623daab
commit 41c7ddab3eae931880190af714c5506b4488ffb8

bohuzel mi nefunguje automaticke obnovovani certifikatu, tak to budu muset ruco, musim si udelat poznamku do kalendare:)
