### ISSUE TITLE
Nejde přesunout rozcestník - 400 Bad request

### ISSUE THREAD

**Issue by mkyral** [osmcz/api#26]
Rozcestník JE275 ( http://openstreetmap.cz/#map=16/50.2104/16.9903 ) nejde přesunout.
Po kliknutí na tlačítko "Přesunout sem" postranní panel zmizí, ale požadavek skončí s chybou 400.

![gp_move1](https://cloud.githubusercontent.com/assets/155542/16204591/e62a8832-371f-11e6-8863-530ea848915c.png)
![gp_move2](https://cloud.githubusercontent.com/assets/155542/16204596/ea18b63a-371f-11e6-8d45-d621d8d0a92d.png)

Viz diskuze na @talk-cz
> Dne 20.6.2016 v 18:29 Zdeněk Pražák napsal(a):
> ono to nefunguje i v jiných případech
> U rozcestníku ref JE275 se po odkliknutí dostanu na http://openstreetmap.cz/#map=16/50.2104/16.9903 a rovněž nemohu rozcestník přesunout na správné souřadnice 50.2133853  16.9928883
>

**Comment by walley** [comment]
presouvani bylo pokazene tak nejak uplne, byla chyba ve volani move api, (mel sem tak move_photo, tak se ale menuje fce co to vykonava:) driv to slo ale pak sem to predelal a uz to neslo. je to opraveny ale musi se deploynout jinak to pujde jen na demu.
