### ISSUE TITLE
api call na vraceni sekvence rozcestniku, tudiz zobrazeni cele trasy 

### ISSUE THREAD

**Issue by walley** [osmcz/api#3]
napr /seq/OL200 - vrati vsechno od ol200 do ol299 pokud to existuje
(to me ted napadlo, citim se nyni velmi inteligentne)

**Comment by mkyral** [comment]
No nevím jestli to bude vždy celá  trasa - trasy se kříží a rozcestníky sdílejí.
Ale myšlenka je to velmi inteligentní ;-)

**Comment by walley** [comment]
vystup je hnusny, ale hotovo
vlaci to vsech 1000 rozcestniku naraz, 

http://api.openstreetmap.cz/table/sequence/ol
