### ISSUE TITLE
openid editor - podivné chování

### ISSUE THREAD

**Issue by mkyral** [osmcz/api#31]
Tak jsem chtěl upravit rozcestník, který jsem nahrál přes aplikaci:
https://api.openstreetmap.cz/table/id/8612

Vzpomněl jsem si na openid, takže jsem v url přepsal table na openid. Normálně jsem se přihlásil, ale editor pak vypadal opravdu hodně zvláštně:

![openid_editor](https://cloud.githubusercontent.com/assets/155542/16961165/9e51cdac-4dec-11e6-9fa8-bba698a1d455.png)

Klikl jsem do pole ref, zadal jej a klikl na OK. Zase se objevilo pole pro vložení openid url:
![openid_editor_2](https://cloud.githubusercontent.com/assets/155542/16961187/b867816e-4dec-11e6-9326-3aa3e3599900.png)

Jenže když jsem do něj klikl, nenabídlo mi to možnost tam to openid url zapsat, ale objevilo se toto:
![openid_editor_3](https://cloud.githubusercontent.com/assets/155542/16961210/d088cf46-4dec-11e6-95eb-56a4a812b430.png)

Řekl bych, že je to rozbité ;-)

**Comment by walley** [comment]
ajax call zapomene prihlaseni
neco se mu musi podstrcit aby to nedelal.

**Comment by walley** [comment]
pri klasickem prihlaseni a kliknuti na id se ta sama stranka zobrazi normalne, pri tomhle priohnuti se mu tam nekde strati session id nebo neco podobneho, nebo vznikne pro uplne jinou stranku.

asi se musi udelat kontrola usera jeste pred pokusem zobrazit cokoliv a nabidnout prihlaseni okamzite.

**Comment by mkyral** [comment]
Tak přiohnutí - jen jsem přepsal pár písmenek, protože z osmap.cz se mi otevřelo něco jiného ;-).

Chtělo by to už nějak vymyslet tu integraci na osmap.cz. Abych nic přiohýbat nemusel a rovnou se mi otevřela správná verze formuláře.

**Comment by walley** [comment]
no na integraci sem uz udelal chybu #30 (to je zaklad:)

jinak zadrhel je v tom ze session_id se predava prez cookie a ta cookie se nastavi s blbou cestou, takze ji ty cally nedostanou a chcou se autorizovat extra znovu

**Comment by walley** [comment]
tohle je kus dokumentace mod_openid: a je to asi to co chceme.

AuthOpenIDCookiePath: Explicitly set the path of the auth cookie (for instance, if you want to explicitly grant access to a location other than the one the user is trying to access).

**Comment by walley** [comment]
mam pocit ze ta direktiva pomohla, zkus to, ale bud musis pockat nez to prihlaseni vyprsi, nebo to cookie smazat

**Comment by mkyral** [comment]
Mám něco lepšího. Mám jiný počítač :-D
Tak jsem zkusil a zatím to vypadá, že to funguje.
