### ISSUE TITLE
Openid - nefunguje přihlášení

### ISSUE THREAD

**Issue by mkyral** [osmcz/api#34]
Tak jsem opět chtěl v editoru upravit  data jednoho rozcestníku. Konkrétně: https://api.openstreetmap.cz/table/id/8323

Přepsal jsem table na openid, objevila se mi výzva k přihlášení, zadal jsem url na  mojeid.cz, objevila se stránka zda chci přihlásit k https://api.openstreetmap.cz/openid/id/.

Klikl jsem na "OK" a místo editoru zase vyskočila stránka s přihlášením. Je problém u mne nebo na serveru?

**Comment by mkyral** [comment]
Možná zase problém https vs. http :-(

```
Načítání smíšeného (nezabezpečeného) zobrazovaného obsahu na zabezpečené stránce "http://www.openid.net/login-bg.gif"[Zjistit více] 8323
Načítání smíšeného (nezabezpečeného) zobrazovaného obsahu na zabezpečené stránce "http://openid.net/images/login-bg.gif"[Zjistit více]
```

**Comment by walley** [comment]
to vypada ze budeme muset udelat vlastni prihlasovaci stranku (tu kde se zadava openid id), nebot obsahuje mixed content. 

Nemel by to byt velky problem, cela ta vec je na to pripravena.

**Comment by walley** [comment]
udelana custom html page bez http, same https (vadil tam tomu stene akorat jeden mizerny obrazek). 
Musel sem pridelat i nejaky js a snad to funguje

**Comment by mkyral** [comment]
Díky.
Vyzkoušel jsem. Nejprve to blblo, pak jsem smazal cookies a teprve potom to začalo fungovat. Budu průběžně testovat a kdyby něco, tak se ozvu,

**Comment by walley** [comment]
ok
