### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by severak** [osmcz/api#37]
JSON výstup bych spíš dal jako objekt (nebo pole objektů) než jako pole polí, např:

```
GET https://api.openstreetmap.cz/table/id/15?output=json

{ 
    "id": 15,
    "lat": 49.6245333333333,
    "lon": 12.5715416666667,
    "url":  "img/guidepost/DSC00362.JPG",
    "name" :  "DSC00362.JPG",
    "attribution": "Petr Dlouhy",
    "ref": "TC072"
}
```

místo současného

```
GET https://api.openstreetmap.cz/table/id/15?output=json

[[15,49.6245333333333,12.5715416666667,"img/guidepost/DSC00362.JPG","DSC00362.JPG","Petr Dlouhy","TC072",null,null]]
```

**Comment by walley** [comment]
hmm momentaqlne to je json z perliho selectall_arrayref nijak neupravovany,
muze to vracet i vice vysledku takze bud objekt objektu nebo objekt poli nebo pole objektu ...

asi bych udelal nejaky dalsi menic vystupu, ktery by ridil jak to udelat, ale jestli to nenapise nekdo jinej, tak to vidim hodne blede ...

**Comment by severak** [comment]
@walley Můžu napsat měnič výstupu. Akorát nevím, zda to dám v perlu.

**Comment by walley** [comment]
asi v podstate neni potreba ...
