### ISSUE TITLE
Diakritika - nekonzistence API

### ISSUE THREAD

**Issue by mkyral** [osmcz/api#39]
Když nahraji fotku přes guidepost.php, tak se mi ořeže diakritika. Ze ŠU123 se mi stane U123. Ovšem při následné editaci fotky v editoru už není problém změnit ref na ŠU123 a přidat štítek ref:šu123.

@walley: jak by to mělo být? Plná podpora diakritiky?

**Comment by walley** [comment]
plna podpora unicode, resp utf8, musis pridat do sanitizace cesky znaky

**Comment by mkyral** [comment]
Ok. Až bude čas (a vzpomenu si na to), tak to přidám.

**Comment by walley** [comment]
\p{L}
\p{IsLatin}
nekdy v budoucnu, je to lepsi nez vypisovat znaky
