### ISSUE TITLE
strankovani html output

### ISSUE THREAD

**Issue by walley** [osmcz/api#42]

**Comment by walley** [comment]
strankovat jde prez parametry limit a offset uz ted (pokud to funguje;)

**Comment by walley** [comment]
skoro hotovo, starcraft je zadarmo, asi se to protahne:)

**Comment by mkyral** [comment]
Tak ono to stránkování sice funguje, ale jen když mu explicitně vnutím parametry. A to je trochu problém, když mně přihlášení přes openid přesměruje na editor namísto původně volané adresy.

**Comment by walley** [comment]
strankovani hotovo.
to s tim openid je chyba a nerozumim tomu, muzes otevrit novou issue a popsat to presneji?

**Comment by walley** [comment]
asi uz tomu rozumim ale stejno to vytvor jestli tomu rozumim spravne, 
pokud tam zadas znovu to puvodni url, tak uz si korektne prihlasen.
