### ISSUE TITLE
Po přihlášení přes openid se api nevrátí na předchozí url

### ISSUE THREAD

**Issue by mkyral** [osmcz/api#44]
1. Na osmap.cz si zobrazím nějaký rozcestník, třeba https://api.openstreetmap.cz/table/id/7699
2. V url změním table na openid: https://api.openstreetmap.cz/openid/id/7699
3. Zobrazí se přihlašovací formulář: https://api.openstreetmap.cz/login.html?modauthopenid.referrer=https%3A%2F%2Fapi.openstreetmap.cz%2Fopenid%2Fid%2F7699%3F
4. Přihlásím se

Následně se mi zobrazí stránka https://api.openstreetmap.cz/webapps/editor.html?login=openid&xpage=0 namísto očekávané https://api.openstreetmap.cz/openid/id/7699

**Comment by walley** [comment]
tohle vyresi univerzalni login page
