### ISSUE TITLE
Editor: odkaz na smazání fotky: vrací 401 - 

### ISSUE THREAD

**Issue by mkyral** [osmcz/api#45]
Rozmazanou a nečitelnou fotku rozcestníku https://api.openstreetmap.cz/openid/id/1002 jsem nahradil novou: https://api.openstreetmap.cz/openid/id/12063

Teď bych rád smazal tu starou fotku (@walley : tahle se ti fakt moc nepovedla ;-) ).
Ovšem po kliknutí na odkaz pro smazání se nic nestane. A to ani v table ani v openid režimu.

Respektive, ona se zavolá url: https://api.openstreetmap.cz/openid/remove/1002 ale server odpoví 
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>You can not do this</h1>
<p>to me:(</p>
<hr>
<address>openstreetmap.cz/2 Ulramegasuperdupercool/0.0.1 Server at api.openstreetmap.cz Port 80</address>
</body></html>
```

Což je nějaká chyba, protože co si pamatuji, tak to kdysi fungovalo. A další problém je, že normální uživatel se o tom nikdy nedozví (že je něco špatně).

**Comment by walley** [comment]
to je spravne

**Comment by walley** [comment]
ta fitka navic ukazuje predchozi stav takze bych ji tam nechal:)

**Comment by mkyral** [comment]
> to je spravne

Nerozumím. Vždyť to přece předtím jen označilo fotku "na smazání" a stejně se to muselo následně potvrdit. Mám to brát tak, že tě sralo, že si lidi dovolují požadovat smazání nekvalitních fotek? Vždyť přece hlavním cílem by mělo být mít databázi kvalitních fotek. Takže pokud je k dispozici kvalitnější, tak by mělo být možné minimálně skrýt nekvalitní fotku.

> ta fitka navic ukazuje predchozi stav takze bych ji tam nechal:)

Fitka?

V každém případě není moc uživatelsky přívětivé, když je v editoru volba "delete", která "nic nedělá". Pokud volání vrátí chybu, mělo by se ta chyba nějak rozumně zobrazit, aby uživatel hned věděl na čem je.

A pokud API obsahuje metodu delete, která "nefunguje", tak je taková metoda na dvě věci.

**Comment by walley** [comment]
na provedeni api funkce delete je potreba specialni opravneni, ktere mam technicky ted jen ja. 
ta akce by mela pro ostatni vracet korektne http status 401  Unauthorized (jelikoz to sem pastujes tak to asi funguje). http statusy nejsou chyby, je to odpoved serveru na dotaz, takze to "funguje" jak ma, jen to bylo spatne popsano. Ten cudl delete tam uz davno nemel byt, jen sem pri pokusu odtranit ho udelal chybu.

mazani se provadi jen v pripade ze to ma smysl, nejsme wikipedie:
- fotka je nelegalni, na fotce sou osoby, ktere tam nechteji byt.
- duplikaty, nebo fotka byla nahrazena lepsi, zobrazujici rozcestnik ve stejnem stavu. 

(ta hnusna o ktere se bavime je jina, pravdepodobne starsi, nez ta co ji nahrazuje)

fitka=fotka

editor byl upraven, mazani bylo odstraneno, misto toho je nahlaseni zavadneho obsahu mailem.

taky sem upravil popis api aby bylo jasne ze delete je specialni.

v podstate z toho plyne:
 ano, chceme rozmazany fotky a nebudeme je mazat, pokud maji nejakou informacni hodnotu.
