### ISSUE TITLE
Znak # v názvu souboru způsobí, že soubor nelze zobrazit

### ISSUE THREAD

**Issue by mkyral** [osmcz/api#46]
Uživatel nahrál soubor pojmenovaný [VO 493 2 2015.07.10#56 Pod Boubínem 1352 m.jpg](http://api.openstreetmap.cz/img/guidepost/VO%20493%202%202015.07.10#56%20Pod%20Boub%C3%ADnem%201352%20m.jpg). Znak '#' v názvu způsobil, že se na soubor nelze odkázat. Server vrátí chybu:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /img/guidepost/VO 493 2 2015.07.10 was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Debian) DAV/2 SVN/1.6.17 PHP/5.4.45-0+deb7u8 mod_ssl/2.2.22 OpenSSL/1.0.1t mod_apreq2-20090110/2.8.0 mod_perl/2.0.7 Perl/v5.14.2 Server at api.openstreetmap.cz Port 80</address>
</body></html>
```

**Comment by mkyral** [comment]
V [github.com/vvito/chyrp](https://github.com/vito/chyrp/blob/master/includes/helpers.php) jsem našel tuhle pěknou funkci:
```php
/**
  * Function: sanitize
  * Returns a sanitized string, typically for URLs.
  *
  * Parameters:
  *     $string - The string to sanitize.
  *     $force_lowercase - Force the string to lowercase?
  *     $anal - If set to *true*, will remove all non-alphanumeric characters.
  *     $trunc - Number of characters to truncate to (default 100, 0 to disable).
  */
################################################################################
function sanitize($string, $force_lowercase = true, $anal = false, $trunc = 100) {
    $strip = array("~", "`", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "_", "=", "+", "[", "{", "]",
                    "}", "\\", "|", ";", ":", "\"", "'", "&#8216;", "&#8217;", "&#8220;", "&#8221;", "&#8211;", "&#8212;",
                    "—", "–", ",", "<", ".", ">", "/", "?");
    $clean = trim(str_replace($strip, "", strip_tags($string)));
    $clean = preg_replace('/\s+/', "-", $clean);
    $clean = ($anal ? preg_replace("/[^a-zA-Z0-9]/", "", $clean) : $clean);
    $clean = ($trunc ? substr($clean, 0, $trunc) : $clean);
    return ($force_lowercase) ?
        (function_exists('mb_strtolower')) ?
            mb_strtolower($clean, 'UTF-8') :
            strtolower($clean) :
        $clean;
}
```

Ale nejsem si jist, zda je dobré ji nasadit - hrozí vznik duplicit. Když někdo nahraje stejný soubor podruhé, tak může mít jiné jméno a projde tak přes kontrolu.

Možná bude statšit jen přidat do kontroly #, závorky a další rezervované znaky .

**Comment by walley** [comment]
duplicity by se meli kontrolovat taky, jmeno souboru je hlavni identifikator, zadne duplicity nastat nemuzou

**Comment by mkyral** [comment]
Ne. Myslím to tak, že když někdo nahrál soubor s nějakým podivným jménem, tak teď jej bude moci nahrát znova, protože se ta jména nebudou rovnat.

Ale těch případů asi nebude moc, pokud vůbec nejaký.

**Comment by walley** [comment]
ano, to je pravda.

nicmene v tomto pripade by se tak stat nemelo protoze:
fotka se puvodne jmenovala (redakcne zkraceno:)
a#b.jpg
upravil sem to na ab.jpg
pri pokusu nahrat to znovu se to automaticky upravi na 
ab.jpg
a pri odmazani mrizky je z toho zase
ab.jpg
takze v tomhle pripade by se muselo jmeno uplne predelat aby se to zase uploadlo.

**Comment by mkyral** [comment]
A můžeš teda smazat ty duplicity?

http://api.openstreetmap.cz/table/id/12082
http://api.openstreetmap.cz/table/id/12084

http://api.openstreetmap.cz/table/id/12083
http://api.openstreetmap.cz/table/id/12085

Díky

**Comment by walley** [comment]
jo tak ono to tam uz 2x je, to sem nevedel, kterej nazev teda nechat, ten kratsi?

**Comment by mkyral** [comment]
Ono to je jedno. Hoď si korunou ;-)

**Comment by walley** [comment]
done
