### ISSUE TITLE
projekty

### ISSUE THREAD

**Issue by walley** [osmcz/api#47]
podpora pro projekty, subprojekty nebo tak nejak.
je nutno ziskat moznost pracovat nad podmnozinou fotek. momentalne je takova to podmnozina turisticke rozcestniky. 
bude existovat nejaky spravce nebo to muze delat kazdy, ktery vycleni fotky a api pak bude pracovat jen nad timto subsetem. 

vyresi to problemy v kontrolach rozcestniku. v subsetu budou jen ty aktualni a perfektne zaostrene:) fotografie. pujde je take "mazat" vyrazenim ze subsetu.

cele se to zapne nejakym parametrem v api callu.
pokud bude parametr pritomen, fotky z jinych setu jakoby nebudou existovat.

**Comment by mkyral** [comment]
Však na to stačí tagy ne? Ten nový formulář dává všem rozcestníkům automaticky tag "`rozcestnik`".
A neaktuální fotky už teď dostávají tag "`zruseno`". Což je podle mně spíš o tom, že byl zrušen rozcestník jako takový, ale ostatní to chápou jinak, Případně je možné zavést tag "`historicka`" (fotka).

A jak tak nad tím uvažuji, můžeme to i předělat podle ref. Tedy:
```
typ:rozcesnik
typ:infotabule
typ:mapa
typ:panorama
…
```

A api by se mohlo rozšířit o parametry `&type=rozcestnik&history=false`

Pokud se to udělá synchronizovaně s podporou v aplikaci na osmap.cz, tak by mohl být přechod bezproblémový.

@tkas co myslíš?

**Comment by walley** [comment]
praveze tagy nestaci. tohle vyrobi presne to co porad chcete. jednu fotku na rozcestnik. a moznost delat analyzu nad setem relevantnich fotek.
na zacatku se tam nacpe vsechno s tagem rozcrstnik a pak uz to pojede. a to co ty mas jako type=rozcestnik je presne ono.

**Comment by mkyral** [comment]
Tak k čemu ty tagy teda jsou? :-D

Ona to nemusí být jen jedna fotka na rozcestník. Fotek může být více - z různých stran, z blízka i dáli. Už nějakou dobu se chystám přidat podporu pro zobrazování více fotek. Jen se k tomu dostat.

Nakonec `type=rozcestnik` můžeš v pohodě převést na `and tag='rozcestnik'` nebo `and tag='type' and value='rozcestnik'`.

A pokud teda budeš rozšiřovat strukturu databáze, tak se přimlouvám za sloupce `type/group/space` a `archived/historic/obsole=Yes/No`, datum vložení a datum pořízení - je jedno jak se ty sloupce budou jmenovat.

**Comment by walley** [comment]
je to k tomu aby byl logicky oddelen set fotek, v podstate to vyresi problem osmhicheck protoze bude moznost odfiltrovat fotky navzdy aniz by se musely smazat.

typycky most a zastavka, aby to mohl preskakovat tak si vyrobil tag prehledova. co to je? kdo vi. takhle si je vymaze ze sveho setu a nebude problem. novy uploadovatko rozcestniku uz bude automaticky pracovat jen z rozcestnikovym setem. 
a nebude problem udelat vrstvu mostu s uploadovatkem na set mostu.
v podstate to idealne funguje s uploadovaci ikonkou objevujici se u zobrazene vrstvy a mizejici kdyz se vrstva schova.
muzem udelat projekt na fotky rozhleden a s touhle infrastrukturou to bude znamenat jen vyrobit ikonu rozhledny na uploadovaci tlacitko.

me osobne tagy staci, jinym ne, tak proc jim nevyjit vstric.

**Comment by mkyral** [comment]
> me osobne tagy staci, jinym ne, tak proc jim nevyjit vstric.

Trochu se obávám, aby už nebylo pozdě.

**Comment by walley** [comment]
nikdy neni pozde

**Comment by walley** [comment]
zadne zmeny praveze nebudou, 
proste kdyz se ten extra parametr nepouzije, bude vsechno jako driv

**Comment by walley** [comment]
konecne sem zacal na tomhle delat.

ukazka:
http://api.openstreetmap.cz/table/all?project=2

projekty budou pojmenovany textove, a bude se dat vylistovat jejich seznam
http://api.openstreetmap.cz/table/project pro zacatek pouze takto

**Comment by severak** [comment]
http://api.openstreetmap.cz/table/project vypisuje:

> The server made a boo boo.

**Comment by walley** [comment]
work in progress:)
http://api.openstreetmap.cz/table/projectlist je finalni vypis projektu.
do konce tydne by to mohlo zacit fungovat vsechno

**Comment by walley** [comment]
tak vsechno asi fungovat nezacne, nicmene:
tady
http://api.openstreetmap.cz/webapps/projectlist/projectlist.html
je jednoduchy xicht pro vyrabeni projektu ve smyslu jmena (krome mazani, to uz sem nestihl, mam hlad a jedu na obed).

odkazy v seznamu funguji a lze prohlizet fotky prirazene do projektu.

pro predstavu jak to bude fungovat.

sprava prirazeni fotek k projektu jeste hotova neni, na testovani je neco v prvnich 3 projektech.

**Comment by walley** [comment]
http://api.openstreetmap.cz/webapps/project/project.html
 na spravu fotek v projektu
dneska bych mohl dodelat mazani
je nutno pridelat overovani nejakou formou

jinak to zhruba funguje

**Comment by walley** [comment]
mazani uz taky funguje
ted na to zkusim naroubovat oauth, ale jestli to pujde netusim:)
jinak tam pridam nejaky heslo pro pridavani a ubirani,

**Comment by walley** [comment]
v  podstate hotovo, jen bez auth
